// Generated by gencpp from file random_walk/AddTwoInts.msg
// DO NOT EDIT!


#ifndef RANDOM_WALK_MESSAGE_ADDTWOINTS_H
#define RANDOM_WALK_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <random_walk/AddTwoIntsRequest.h>
#include <random_walk/AddTwoIntsResponse.h>


namespace random_walk
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace random_walk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::random_walk::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::random_walk::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::random_walk::AddTwoInts > {
  static const char* value()
  {
    return "random_walk/AddTwoInts";
  }

  static const char* value(const ::random_walk::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::random_walk::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::random_walk::AddTwoInts >
template<>
struct MD5Sum< ::random_walk::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::random_walk::AddTwoInts >::value();
  }
  static const char* value(const ::random_walk::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::random_walk::AddTwoIntsRequest> should match
// service_traits::DataType< ::random_walk::AddTwoInts >
template<>
struct DataType< ::random_walk::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::random_walk::AddTwoInts >::value();
  }
  static const char* value(const ::random_walk::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::random_walk::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::random_walk::AddTwoInts >
template<>
struct MD5Sum< ::random_walk::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::random_walk::AddTwoInts >::value();
  }
  static const char* value(const ::random_walk::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::random_walk::AddTwoIntsResponse> should match
// service_traits::DataType< ::random_walk::AddTwoInts >
template<>
struct DataType< ::random_walk::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::random_walk::AddTwoInts >::value();
  }
  static const char* value(const ::random_walk::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RANDOM_WALK_MESSAGE_ADDTWOINTS_H
